---
title: Ausnahmen
ms.date: 03/30/2017
ms.assetid: 065205cc-52dd-4f30-9578-b17d8d113136
ms.openlocfilehash: 53cc8e3e27e131c5c2a9f8271851a0d8d7e0cbd7
ms.sourcegitcommit: bc293b14af795e0e999e3304dd40c0222cf2ffe4
ms.translationtype: MT
ms.contentlocale: de-DE
ms.lasthandoff: 11/26/2020
ms.locfileid: "96280207"
---
# <a name="exceptions"></a><span data-ttu-id="4baf1-102">Ausnahmen</span><span class="sxs-lookup"><span data-stu-id="4baf1-102">Exceptions</span></span>

<span data-ttu-id="4baf1-103">Die <xref:System.Activities.Statements.TryCatch>-Aktivität kann zur Behandlung von Ausnahmen verwendet werden, die während der Ausführung eines Workflows ausgelöst werden.</span><span class="sxs-lookup"><span data-stu-id="4baf1-103">Workflows can use the <xref:System.Activities.Statements.TryCatch> activity to handle exceptions that are raised during the execution of a workflow.</span></span> <span data-ttu-id="4baf1-104">Diese Ausnahmen können behandelt oder mit der <xref:System.Activities.Statements.Rethrow>-Aktivität erneut ausgelöst werden.</span><span class="sxs-lookup"><span data-stu-id="4baf1-104">These exceptions can be handled or they can be re-thrown using the <xref:System.Activities.Statements.Rethrow> activity.</span></span> <span data-ttu-id="4baf1-105">Aktivitäten im Abschnitt <xref:System.Activities.Statements.TryCatch.Finally%2A> werden nach Abschluss des Abschnitts <xref:System.Activities.Statements.TryCatch.Try%2A> oder des Abschnitts <xref:System.Activities.Statements.TryCatch.Catches%2A> ausgeführt.</span><span class="sxs-lookup"><span data-stu-id="4baf1-105">Activities in the <xref:System.Activities.Statements.TryCatch.Finally%2A> section are executed when either the <xref:System.Activities.Statements.TryCatch.Try%2A> section or the <xref:System.Activities.Statements.TryCatch.Catches%2A> section completes.</span></span> <span data-ttu-id="4baf1-106">Von einer-Instanz gehostete Workflows <xref:System.Activities.WorkflowApplication> können auch den- <xref:System.Activities.WorkflowApplication.OnUnhandledException%2A> Ereignishandler verwenden, um Ausnahmen zu behandeln, die nicht von einer-Aktivität behandelt werden <xref:System.Activities.Statements.TryCatch> .</span><span class="sxs-lookup"><span data-stu-id="4baf1-106">Workflows hosted by a <xref:System.Activities.WorkflowApplication> instance can also use the <xref:System.Activities.WorkflowApplication.OnUnhandledException%2A> event handler to handle exceptions that are not handled by a <xref:System.Activities.Statements.TryCatch> activity.</span></span>  
  
## <a name="causes-of-exceptions"></a><span data-ttu-id="4baf1-107">Ursachen von Ausnahmen</span><span class="sxs-lookup"><span data-stu-id="4baf1-107">Causes of Exceptions</span></span>  

 <span data-ttu-id="4baf1-108">In einem Workflow können Ausnahmen auf die folgenden Weisen generiert werden:</span><span class="sxs-lookup"><span data-stu-id="4baf1-108">In a workflow, exceptions can be generated in the following ways:</span></span>  
  
- <span data-ttu-id="4baf1-109">Ein Timeout von Transaktionen in <xref:System.Activities.Statements.TransactionScope>.</span><span class="sxs-lookup"><span data-stu-id="4baf1-109">A time-out of transactions in <xref:System.Activities.Statements.TransactionScope>.</span></span>  
  
- <span data-ttu-id="4baf1-110">Eine explizite vom Workflow mit der <xref:System.Activities.Statements.Throw>-Aktivität ausgelöste Ausnahme.</span><span class="sxs-lookup"><span data-stu-id="4baf1-110">An explicit exception thrown by the workflow using the <xref:System.Activities.Statements.Throw> activity.</span></span>  
  
- <span data-ttu-id="4baf1-111">Eine von einer Aktivität ausgelöste [!INCLUDE[netfx_current_short](../../../includes/netfx-current-short-md.md)]-Ausnahme.</span><span class="sxs-lookup"><span data-stu-id="4baf1-111">A [!INCLUDE[netfx_current_short](../../../includes/netfx-current-short-md.md)] exception thrown from an activity.</span></span>  
  
- <span data-ttu-id="4baf1-112">Eine von externem Code ausgelöste Ausnahme, z. B. Bibliotheken, Komponenten oder Dienste, die im Workflow verwendet werden.</span><span class="sxs-lookup"><span data-stu-id="4baf1-112">An exception thrown from external code, such as libraries, components, or services that are used in the workflow.</span></span>  
  
## <a name="handling-exceptions"></a><span data-ttu-id="4baf1-113">Behandeln von Ausnahmen</span><span class="sxs-lookup"><span data-stu-id="4baf1-113">Handling Exceptions</span></span>  

 <span data-ttu-id="4baf1-114">Wenn eine Ausnahme von einer Aktivität ausgelöst und nicht behandelt wird, ist das Beenden der Workflowinstanz das Standardverhalten.</span><span class="sxs-lookup"><span data-stu-id="4baf1-114">If an exception is thrown by an activity and is unhandled, the default behavior is to terminate the workflow instance.</span></span> <span data-ttu-id="4baf1-115">Wenn ein benutzerdefinierter <xref:System.Activities.WorkflowApplication.OnUnhandledException%2A>-Handler vorhanden ist, kann dieser das Standardverhalten überschreiben.</span><span class="sxs-lookup"><span data-stu-id="4baf1-115">If a custom <xref:System.Activities.WorkflowApplication.OnUnhandledException%2A> handler is present, it can override this default behavior.</span></span> <span data-ttu-id="4baf1-116">Mit diesem Handler kann der Autor des Workflowhosts die angemessene Behandlung bereitstellen, z. B. benutzerdefinierte Protokollierung, Abbruch des Workflows oder Beenden des Workflows.</span><span class="sxs-lookup"><span data-stu-id="4baf1-116">This handler gives the workflow host author an opportunity to provide the appropriate handling, such as custom logging, aborting the workflow, canceling the workflow, or terminating the workflow.</span></span>  <span data-ttu-id="4baf1-117">Wenn ein Workflow eine nicht behandelte Ausnahme auslöst, wird der <xref:System.Activities.WorkflowApplication.OnUnhandledException%2A>-Handler aufgerufen.</span><span class="sxs-lookup"><span data-stu-id="4baf1-117">If a workflow raises an exception that is not handled, the <xref:System.Activities.WorkflowApplication.OnUnhandledException%2A> handler is invoked.</span></span> <span data-ttu-id="4baf1-118">Es gibt drei mögliche Aktionen, die von <xref:System.Activities.WorkflowApplication.OnUnhandledException%2A> zurückgegeben werden und das endgültige Ergebnis des Workflows bestimmen.</span><span class="sxs-lookup"><span data-stu-id="4baf1-118">There are three possible actions returned from <xref:System.Activities.WorkflowApplication.OnUnhandledException%2A> which determine the final outcome of the workflow.</span></span>  
  
- <span data-ttu-id="4baf1-119">**Abbrechen** -eine abgebrochene Workflow Instanz ist ein ordnungsgemäßes Beenden einer Verzweigungs Ausführung.</span><span class="sxs-lookup"><span data-stu-id="4baf1-119">**Cancel** - A cancelled workflow instance is a graceful exit of a branch execution.</span></span> <span data-ttu-id="4baf1-120">Sie können das Abbruchverhalten anpassen (z. B. durch Verwendung einer CancellationScope-Aktivität).</span><span class="sxs-lookup"><span data-stu-id="4baf1-120">You can model cancelation behavior (for example, by using a CancellationScope activity).</span></span> <span data-ttu-id="4baf1-121">Der Completed-Handler wird aufgerufen, wenn der Abbruchprozess abgeschlossen wird.</span><span class="sxs-lookup"><span data-stu-id="4baf1-121">The Completed handler is invoked when the cancellation process completes.</span></span> <span data-ttu-id="4baf1-122">Ein abgebrochener Workflow befindet sich im Cancelled-Zustand.</span><span class="sxs-lookup"><span data-stu-id="4baf1-122">A cancelled workflow is in the Cancelled state.</span></span>  
  
- <span data-ttu-id="4baf1-123">**Beenden** -eine beendete Workflow Instanz kann nicht fortgesetzt oder neu gestartet werden.</span><span class="sxs-lookup"><span data-stu-id="4baf1-123">**Terminate** - A terminated workflow instance cannot be resumed or restarted.</span></span>  <span data-ttu-id="4baf1-124">Dadurch wird das Completed-Ereignis ausgelöst, in dem Sie eine Ausnahme als Grund für die Beendigung bereitstellen können.</span><span class="sxs-lookup"><span data-stu-id="4baf1-124">This triggers the Completed event in which you can provide an exception as the reason it was terminated.</span></span> <span data-ttu-id="4baf1-125">Der Terminated-Handler wird aufgerufen, wenn der Beendigungsprozess abgeschlossen wird.</span><span class="sxs-lookup"><span data-stu-id="4baf1-125">The Terminated handler is invoked when the termination process completes.</span></span> <span data-ttu-id="4baf1-126">Ein beendeter Workflow befindet sich im Faulted-Zustand.</span><span class="sxs-lookup"><span data-stu-id="4baf1-126">A terminated workflow is in the Faulted state.</span></span>  
  
- <span data-ttu-id="4baf1-127">**Abbrechen-eine abgebrochene** Workflow Instanz kann nur fortgesetzt werden, wenn Sie als persistent konfiguriert wurde.</span><span class="sxs-lookup"><span data-stu-id="4baf1-127">**Abort** - An aborted workflow instances can be resumed only if it has been configured to be persistent.</span></span>  <span data-ttu-id="4baf1-128">Ohne Persistenz kann ein Workflow nicht fortgesetzt werden.</span><span class="sxs-lookup"><span data-stu-id="4baf1-128">Without persistence, a workflow cannot be resumed.</span></span>  <span data-ttu-id="4baf1-129">An dem Punkt, an dem ein Workflow abgebrochen wird, gehen alle seit dem letzten Persistenzpunkt verarbeiteten Daten (im Arbeitsspeicher) verloren.</span><span class="sxs-lookup"><span data-stu-id="4baf1-129">At the point a workflow is aborted, any work done (in memory) since the last persistence point will be lost.</span></span> <span data-ttu-id="4baf1-130">Für einen abgebrochenen Workflow wird der Aborted-Handler unter Verwendung der Ausnahme als Grund ausgelöst, wenn der Abbruchprozess beendet wird.</span><span class="sxs-lookup"><span data-stu-id="4baf1-130">For an aborted workflow, the Aborted handler is invoked using the exception as the reason when the abort process completes.</span></span> <span data-ttu-id="4baf1-131">Im Gegensatz zum Cancelled- und Terminated-Handler wird der Completed-Handler jedoch nicht aufgerufen.</span><span class="sxs-lookup"><span data-stu-id="4baf1-131">However, unlike Cancelled and Terminated, the Completed handler is not invoked.</span></span> <span data-ttu-id="4baf1-132">Ein abgebrochener Workflow befindet sich in einem Aborted-Zustand.</span><span class="sxs-lookup"><span data-stu-id="4baf1-132">An aborted workflow is in an Aborted state.</span></span>  
  
 <span data-ttu-id="4baf1-133">Im folgenden Beispiel wird ein Workflow aufgerufen, der eine Ausnahme auslöst.</span><span class="sxs-lookup"><span data-stu-id="4baf1-133">The following example invokes a workflow that throws an exception.</span></span> <span data-ttu-id="4baf1-134">Die Ausnahme wird vom Workflow nicht behandelt, und der <xref:System.Activities.WorkflowApplication.OnUnhandledException%2A>-Handler wird aufgerufen.</span><span class="sxs-lookup"><span data-stu-id="4baf1-134">The exception is unhandled by the workflow and the <xref:System.Activities.WorkflowApplication.OnUnhandledException%2A> handler is invoked.</span></span> <span data-ttu-id="4baf1-135">Die <xref:System.Activities.WorkflowApplicationUnhandledExceptionEventArgs> werden überprüft, um Informationen zur Ausnahme bereitzustellen, und der Workflow wird beendet.</span><span class="sxs-lookup"><span data-stu-id="4baf1-135">The <xref:System.Activities.WorkflowApplicationUnhandledExceptionEventArgs> are inspected to provide information about the exception, and the workflow is terminated.</span></span>  
  
 [!code-csharp[CFX_WorkflowApplicationExample#1](~/samples/snippets/csharp/VS_Snippets_CFX/cfx_workflowapplicationexample/cs/program.cs#1)]  
  
### <a name="handling-exceptions-with-the-trycatch-activity"></a><span data-ttu-id="4baf1-136">Behandeln von Ausnahmen mit der TryCatch-Aktivität</span><span class="sxs-lookup"><span data-stu-id="4baf1-136">Handling Exceptions with the TryCatch Activity</span></span>  

 <span data-ttu-id="4baf1-137">Zur Behandlung von Ausnahmen innerhalb eines Workflows dient die <xref:System.Activities.Statements.TryCatch>-Aktivität.</span><span class="sxs-lookup"><span data-stu-id="4baf1-137">Handling exceptions inside a workflow is performed with the <xref:System.Activities.Statements.TryCatch> activity.</span></span> <span data-ttu-id="4baf1-138">Die <xref:System.Activities.Statements.TryCatch>-Aktivität verfügt über eine <xref:System.Activities.Statements.TryCatch.Catches%2A>-Auflistung von <xref:System.Activities.Statements.Catch>-Aktivitäten, von denen jede einzelne einem bestimmten <xref:System.Exception>-Typ zugeordnet ist.</span><span class="sxs-lookup"><span data-stu-id="4baf1-138">The <xref:System.Activities.Statements.TryCatch> activity has a <xref:System.Activities.Statements.TryCatch.Catches%2A> collection of <xref:System.Activities.Statements.Catch> activities that are each associated with a specific <xref:System.Exception> type.</span></span> <span data-ttu-id="4baf1-139">Wenn die Ausnahme, die von einer Aktivität im <xref:System.Activities.Statements.TryCatch.Try%2A>-Abschnitt einer <xref:System.Activities.Statements.TryCatch>-Aktivität ausgelöst wurde, der Ausnahme einer <xref:System.Activities.Statements.Catch%601>-Aktivität in der <xref:System.Activities.Statements.TryCatch.Catches%2A>-Auflistung entspricht, wird die Ausnahme behandelt.</span><span class="sxs-lookup"><span data-stu-id="4baf1-139">If the exception thrown by an activity that is contained in the <xref:System.Activities.Statements.TryCatch.Try%2A> section of a <xref:System.Activities.Statements.TryCatch> activity matches the exception of a <xref:System.Activities.Statements.Catch%601> activity in the <xref:System.Activities.Statements.TryCatch.Catches%2A> collection, then the exception is handled.</span></span> <span data-ttu-id="4baf1-140">Wenn die Ausnahme explizit erneut ausgelöst wird oder eine neue Ausnahme ausgelöst wird, erfolgt die Übergabe dieser Ausnahme an die übergeordnete Aktivität.</span><span class="sxs-lookup"><span data-stu-id="4baf1-140">If the exception is explicitly re-thrown or a new exception is thrown then this exception passes up to the parent activity.</span></span> <span data-ttu-id="4baf1-141">Das folgende Codebeispiel zeigt eine <xref:System.Activities.Statements.TryCatch>-Aktivität, mit der eine <xref:System.ApplicationException>-Ausnahme behandelt wird, die im <xref:System.Activities.Statements.TryCatch.Try%2A>-Abschnitt von einer <xref:System.Activities.Statements.Throw>-Aktivität ausgelöst wurde.</span><span class="sxs-lookup"><span data-stu-id="4baf1-141">The following code example shows a <xref:System.Activities.Statements.TryCatch> activity that handles an <xref:System.ApplicationException> that is thrown in the <xref:System.Activities.Statements.TryCatch.Try%2A> section by a <xref:System.Activities.Statements.Throw> activity.</span></span> <span data-ttu-id="4baf1-142">Die Meldung der Ausnahme wird von der <xref:System.Activities.Statements.Catch%601>-Aktivität auf der Konsole ausgegeben. Anschließend wird eine Meldung im <xref:System.Activities.Statements.TryCatch.Finally%2A>-Abschnitt auf der Konsole ausgegeben.</span><span class="sxs-lookup"><span data-stu-id="4baf1-142">The exception's message is written to the console by the <xref:System.Activities.Statements.Catch%601> activity, and then a message is written to the console in the <xref:System.Activities.Statements.TryCatch.Finally%2A> section.</span></span>  
  
 [!code-csharp[CFX_WorkflowApplicationExample#33](~/samples/snippets/csharp/VS_Snippets_CFX/cfx_workflowapplicationexample/cs/program.cs#33)]  
  
 <span data-ttu-id="4baf1-143">Die Aktivitäten im <xref:System.Activities.Statements.TryCatch.Finally%2A>-Abschnitt werden ausgeführt, wenn entweder der <xref:System.Activities.Statements.TryCatch.Try%2A>-Abschnitt oder der <xref:System.Activities.Statements.TryCatch.Catches%2A>-Abschnitt erfolgreich ausgeführt wurde.</span><span class="sxs-lookup"><span data-stu-id="4baf1-143">The activities in the <xref:System.Activities.Statements.TryCatch.Finally%2A> section are executed when either the <xref:System.Activities.Statements.TryCatch.Try%2A> section or the <xref:System.Activities.Statements.TryCatch.Catches%2A> section successfully completes.</span></span> <span data-ttu-id="4baf1-144">Der <xref:System.Activities.Statements.TryCatch.Try%2A>-Abschnitt wird erfolgreich abgeschlossen, sofern er keine Ausnahmen auslöst, und der <xref:System.Activities.Statements.TryCatch.Catches%2A>-Abschnitt wird erfolgreich abgeschlossen, wenn er keine Ausnahmen auslöst oder erneut auslöst.</span><span class="sxs-lookup"><span data-stu-id="4baf1-144">The <xref:System.Activities.Statements.TryCatch.Try%2A> section successfully completes if no exceptions are thrown from it, and the <xref:System.Activities.Statements.TryCatch.Catches%2A> section successfully completes if no exceptions are thrown or rethrown from it.</span></span> <span data-ttu-id="4baf1-145">Wenn im <xref:System.Activities.Statements.TryCatch.Try%2A>-Abschnitt von <xref:System.Activities.Statements.TryCatch> eine Ausnahme ausgelöst und nicht von einem <xref:System.Activities.Statements.Catch%601> im <xref:System.Activities.Statements.TryCatch.Catches%2A>-Abschnitt behandelt wird oder durch <xref:System.Activities.Statements.TryCatch.Catches%2A> erneut ausgelöst wird, werden die Aktivitäten in <xref:System.Activities.Statements.TryCatch.Finally%2A> erst ausgeführt, nachdem eines der folgenden Ereignisse eintritt.</span><span class="sxs-lookup"><span data-stu-id="4baf1-145">If an exception is thrown in the <xref:System.Activities.Statements.TryCatch.Try%2A> section of a <xref:System.Activities.Statements.TryCatch> and is either not handled by a <xref:System.Activities.Statements.Catch%601> in the <xref:System.Activities.Statements.TryCatch.Catches%2A> section, or is rethrown from the <xref:System.Activities.Statements.TryCatch.Catches%2A>, the activities in the <xref:System.Activities.Statements.TryCatch.Finally%2A> will not be executed unless the one of the following occurs.</span></span>  
  
- <span data-ttu-id="4baf1-146">Die Ausnahme wird von einer <xref:System.Activities.Statements.TryCatch>-Workflowaktivität auf einer höheren Ebene abgefangen, unabhängig davon, ob sie von <xref:System.Activities.Statements.TryCatch> auf dieser höheren Ebene erneut ausgelöst wird.</span><span class="sxs-lookup"><span data-stu-id="4baf1-146">The exception is caught by a higher level <xref:System.Activities.Statements.TryCatch> activity in the workflow, regardless of whether it is rethrown from that higher level <xref:System.Activities.Statements.TryCatch>.</span></span>  
  
- <span data-ttu-id="4baf1-147">Die Ausnahme wird nicht von <xref:System.Activities.Statements.TryCatch> auf einer höheren Ebene behandelt, schützt den Stamm des Workflows mit Escapezeichen, und der Workflow wird so konfiguriert, dass er abgebrochen wird, anstatt beendet oder abgebrochen zu werden.</span><span class="sxs-lookup"><span data-stu-id="4baf1-147">The exception is not handled by a higher level <xref:System.Activities.Statements.TryCatch>, escapes the root of the workflow, and the workflow is configured to cancel instead of terminate or abort.</span></span> <span data-ttu-id="4baf1-148">Workflows, die mithilfe von <xref:System.Activities.WorkflowApplication> gehostet werden, können diese Konfiguration vornehmen, indem sie <xref:System.Activities.WorkflowApplication.OnUnhandledException%2A> behandeln und <xref:System.Activities.UnhandledExceptionAction.Cancel> zurückgeben.</span><span class="sxs-lookup"><span data-stu-id="4baf1-148">Workflows hosted using <xref:System.Activities.WorkflowApplication> can configure this by handling <xref:System.Activities.WorkflowApplication.OnUnhandledException%2A> and returning <xref:System.Activities.UnhandledExceptionAction.Cancel>.</span></span> <span data-ttu-id="4baf1-149">Ein Beispiel für die Behandlung von <xref:System.Activities.WorkflowApplication.OnUnhandledException%2A> wurde zuvor in diesem Thema bereitgestellt.</span><span class="sxs-lookup"><span data-stu-id="4baf1-149">An example of handling <xref:System.Activities.WorkflowApplication.OnUnhandledException%2A> is provided previously in this topic.</span></span> <span data-ttu-id="4baf1-150">Workflowdienste können diese Konfiguration vornehmen, indem sie <xref:System.ServiceModel.Activities.Description.WorkflowUnhandledExceptionBehavior> verwenden und <xref:System.ServiceModel.Activities.Description.WorkflowUnhandledExceptionAction.Cancel> angeben.</span><span class="sxs-lookup"><span data-stu-id="4baf1-150">Workflow services can configure this by using <xref:System.ServiceModel.Activities.Description.WorkflowUnhandledExceptionBehavior> and specifying <xref:System.ServiceModel.Activities.Description.WorkflowUnhandledExceptionAction.Cancel>.</span></span> <span data-ttu-id="4baf1-151">Ein Beispiel für das Konfigurieren von <xref:System.ServiceModel.Activities.Description.WorkflowUnhandledExceptionBehavior> finden Sie unter [Erweiterbarkeit des Workflow Dienst Hosts](../wcf/feature-details/workflow-service-host-extensibility.md).</span><span class="sxs-lookup"><span data-stu-id="4baf1-151">For an example of configuring <xref:System.ServiceModel.Activities.Description.WorkflowUnhandledExceptionBehavior>, see [Workflow Service Host Extensibility](../wcf/feature-details/workflow-service-host-extensibility.md).</span></span>  
  
## <a name="exception-handling-versus-compensation"></a><span data-ttu-id="4baf1-152">Ausnahmebehandlung und Kompensierung</span><span class="sxs-lookup"><span data-stu-id="4baf1-152">Exception Handling versus Compensation</span></span>  

 <span data-ttu-id="4baf1-153">Der Unterschied zwischen Ausnahmebehandlung und Kompensierung besteht darin, dass die Ausnahmebehandlung während der Ausführung einer Aktivität erfolgt.</span><span class="sxs-lookup"><span data-stu-id="4baf1-153">The difference between exception handling and compensation is that exception handling occurs during the execution of an activity.</span></span> <span data-ttu-id="4baf1-154">Die Kompensierung erfolgt, nachdem eine Aktivität erfolgreich abgeschlossen wurde.</span><span class="sxs-lookup"><span data-stu-id="4baf1-154">Compensation occurs after an activity has successfully completed.</span></span> <span data-ttu-id="4baf1-155">Die Ausnahmebehandlung bietet eine Möglichkeit, nach dem Auslösen der Ausnahme durch die Aktivität eine Bereinigung durchzuführen. Die Kompensierung dagegen stellt einen Mechanismus bereit, mit dem die erfolgreich abgeschlossene Arbeit einer zuvor abgeschlossenen Aktivität rückgängig gemacht werden kann.</span><span class="sxs-lookup"><span data-stu-id="4baf1-155">Exception handling provides an opportunity to clean up after the activity raises the exception, whereas compensation provides a mechanism by which the successfully completed work of a previously completed activity can be undone.</span></span> <span data-ttu-id="4baf1-156">Weitere Informationen finden Sie unter [Kompensierung](compensation.md).</span><span class="sxs-lookup"><span data-stu-id="4baf1-156">For more information, see [Compensation](compensation.md).</span></span>  
  
## <a name="see-also"></a><span data-ttu-id="4baf1-157">Weitere Informationen</span><span class="sxs-lookup"><span data-stu-id="4baf1-157">See also</span></span>

- <xref:System.Activities.Statements.TryCatch>
- <xref:System.Activities.WorkflowApplication.OnUnhandledException%2A>
- <xref:System.Activities.Statements.CompensableActivity>
