---
title: Ausnahmebehandlung (Task Parallel Library)
description: Erfahren Sie mehr über die Ausnahmebehandlung mit der Task Parallel Library (TPL) in .NET. Unter anderem werden geschachtelte aggregierte Ausnahmen, innere Ausnahmen und nicht überwachte Taskausnahmen behandelt.
ms.date: 04/20/2020
dev_langs:
- csharp
- vb
helpviewer_keywords:
- tasks, exceptions
ms.assetid: beb51e50-9061-4d3d-908c-56a4f7c2e8c1
ms.openlocfilehash: fd16fd4263c092f8678589e1a8dd9544955e798a
ms.sourcegitcommit: 965a5af7918acb0a3fd3baf342e15d511ef75188
ms.translationtype: HT
ms.contentlocale: de-DE
ms.lasthandoff: 11/18/2020
ms.locfileid: "94827333"
---
# <a name="exception-handling-task-parallel-library"></a><span data-ttu-id="b36df-104">Ausnahmebehandlung (Task Parallel Library)</span><span class="sxs-lookup"><span data-stu-id="b36df-104">Exception handling (Task Parallel Library)</span></span>

<span data-ttu-id="b36df-105">Nicht behandelte Ausnahmen, die von innerhalb einer Aufgabe ausgeführtem Benutzercode ausgelöst werden, werden zurück zum aufrufenden Thread geleitet. Hiervon ausgenommen sind bestimmte Szenarios, die weiter unten in diesem Thema beschrieben werden.</span><span class="sxs-lookup"><span data-stu-id="b36df-105">Unhandled exceptions that are thrown by user code that is running inside a task are propagated back to the calling thread, except in certain scenarios that are described later in this topic.</span></span> <span data-ttu-id="b36df-106">Ausnahmen werden weitergegeben, wenn Sie eine der statischen oder instanzbasierten <xref:System.Threading.Tasks.Task.Wait%2A?displayProperty=nameWithType>-Methoden verwenden. Zur Behandlung dieser Ausnahmen schließen Sie den Aufruf in eine `try`/`catch`-Anweisung ein.</span><span class="sxs-lookup"><span data-stu-id="b36df-106">Exceptions are propagated when you use one of the static or instance <xref:System.Threading.Tasks.Task.Wait%2A?displayProperty=nameWithType> methods, and you handle them by enclosing the call in a `try`/`catch` statement.</span></span> <span data-ttu-id="b36df-107">Wenn eine Aufgabe das übergeordnete Element angefügter untergeordneter Aufgaben ist oder wenn Sie auf mehrere Aufgaben warten, können mehrere Ausnahmen ausgelöst werden.</span><span class="sxs-lookup"><span data-stu-id="b36df-107">If a task is the parent of attached child tasks, or if you are waiting on multiple tasks, multiple exceptions could be thrown.</span></span>

<span data-ttu-id="b36df-108">Um alle Ausnahmen zurück an den aufrufenden Thread zu leiten, schließt die Aufgabeninfrastruktur diese in eine <xref:System.AggregateException> -Instanz ein.</span><span class="sxs-lookup"><span data-stu-id="b36df-108">To propagate all the exceptions back to the calling thread, the Task infrastructure wraps them in an <xref:System.AggregateException> instance.</span></span> <span data-ttu-id="b36df-109">Die <xref:System.AggregateException> -Ausnahme verfügt über eine <xref:System.AggregateException.InnerExceptions%2A> -Eigenschaft, die aufgelistet werden kann, um alle ursprünglich ausgelösten Ausnahmen zu analysieren und jede Ausnahme einzeln zu behandeln (bzw. nicht zu behandeln).</span><span class="sxs-lookup"><span data-stu-id="b36df-109">The <xref:System.AggregateException> exception has an <xref:System.AggregateException.InnerExceptions%2A> property that can be enumerated to examine all the original exceptions that were thrown, and handle (or not handle) each one individually.</span></span> <span data-ttu-id="b36df-110">Sie können die ursprünglichen Ausnahmen mithilfe der <xref:System.AggregateException.Handle%2A?displayProperty=nameWithType> -Methode ebenfalls behandeln.</span><span class="sxs-lookup"><span data-stu-id="b36df-110">You can also handle the original exceptions by using the <xref:System.AggregateException.Handle%2A?displayProperty=nameWithType> method.</span></span>

<span data-ttu-id="b36df-111">Auch wenn nur eine Ausnahme ausgelöst wurde, wird diese in eine <xref:System.AggregateException> -Ausnahme eingeschlossen, wie im nachfolgenden Beispiel veranschaulicht.</span><span class="sxs-lookup"><span data-stu-id="b36df-111">Even if only one exception is thrown, it is still wrapped in an <xref:System.AggregateException> exception, as the following example shows.</span></span>

[!code-csharp[TPL_Exceptions#21](../../../samples/snippets/csharp/VS_Snippets_Misc/tpl_exceptions/cs/handling21.cs#21)]
[!code-vb[TPL_Exceptions#21](../../../samples/snippets/visualbasic/VS_Snippets_Misc/tpl_exceptions/vb/handling21.vb#21)]

<span data-ttu-id="b36df-112">Unbehandeltes Ausnahmen vermeiden Sie, indem Sie nur die <xref:System.AggregateException> erfassen und die inneren Ausnahmen nicht beachten.</span><span class="sxs-lookup"><span data-stu-id="b36df-112">You could avoid an unhandled exception by just catching the <xref:System.AggregateException> and not observing any of the inner exceptions.</span></span> <span data-ttu-id="b36df-113">Hiervon wird jedoch abgeraten, da dies dem Erfassen des grundlegenden <xref:System.Exception> -Typs in nicht parallelen Szenarios entspricht.</span><span class="sxs-lookup"><span data-stu-id="b36df-113">However, we recommend that you do not do this because it is analogous to catching the base <xref:System.Exception> type in non-parallel scenarios.</span></span> <span data-ttu-id="b36df-114">Wenn Sie eine Ausnahme erfassen, ohne Maßnahmen zu deren Behandlung zu ergreifen, weist das Programm ggf. einen unbestimmten Zustand auf.</span><span class="sxs-lookup"><span data-stu-id="b36df-114">To catch an exception without taking specific actions to recover from it can leave your program in an indeterminate state.</span></span>

<span data-ttu-id="b36df-115">Wenn Sie die <xref:System.Threading.Tasks.Task.Wait%2A?displayProperty=nameWithType>-Methode nicht aufrufen möchten, um auf den Abschluss einer Aufgabe zu warten, können Sie auch die <xref:System.AggregateException>-Ausnahme der <xref:System.Threading.Tasks.Task.Exception%2A>-Eigenschaft der Aufgabe abrufen, wie im folgenden Beispiel dargestellt.</span><span class="sxs-lookup"><span data-stu-id="b36df-115">If you do not want to call the <xref:System.Threading.Tasks.Task.Wait%2A?displayProperty=nameWithType> method to wait for a task's completion, you can also retrieve the <xref:System.AggregateException> exception from the task's <xref:System.Threading.Tasks.Task.Exception%2A> property, as the following example shows.</span></span> <span data-ttu-id="b36df-116">Weitere Informationen finden Sie im Abschnitt [Beachten von Ausnahmen mit der Task.Exception-Eigenschaft](#observing-exceptions-by-using-the-taskexception-property) dieses Themas.</span><span class="sxs-lookup"><span data-stu-id="b36df-116">For more information, see the [Observing exceptions by using the Task.Exception property](#observing-exceptions-by-using-the-taskexception-property) section in this topic.</span></span>

[!code-csharp[TPL_Exceptions#29](../../../samples/snippets/csharp/VS_Snippets_Misc/tpl_exceptions/cs/handling22.cs#29)]
[!code-vb[TPL_Exceptions#29](../../../samples/snippets/visualbasic/VS_Snippets_Misc/tpl_exceptions/vb/handling22.vb#29)]

<span data-ttu-id="b36df-117">Wenn Sie nicht auf eine Aufgabe warten, die eine Ausnahme weitergibt, oder auf deren <xref:System.Threading.Tasks.Task.Exception%2A> -Eigenschaft zugreifen, wird die Ausnahme entsprechend der .NET-Ausnahmerichtlinie eskaliert, sofern die Aufgabe der Garbage Collection unterliegt.</span><span class="sxs-lookup"><span data-stu-id="b36df-117">If you do not wait on a task that propagates an exception, or access its <xref:System.Threading.Tasks.Task.Exception%2A> property, the exception is escalated according to the .NET exception policy when the task is garbage-collected.</span></span>

<span data-ttu-id="b36df-118">Wenn Ausnahmen mittels Bubbling wieder an den Verbindungsthread übergeben werden können, ist es möglich, dass eine Aufgabe nach dem Auslösen der Ausnahme weiterhin einige Elemente verarbeitet.</span><span class="sxs-lookup"><span data-stu-id="b36df-118">When exceptions are allowed to bubble up back to the joining thread, it is possible that a task may continue to process some items after the exception is raised.</span></span>

> [!NOTE]
> <span data-ttu-id="b36df-119">Wenn "Nur eigenen Code" aktiviert ist, unterbricht Visual Studio die Ausführung in einigen Fällen in der Zeile, die die Ausnahme auslöst, und eine Fehlermeldung zu einer nicht vom Benutzercode behandelten Ausnahme wird angezeigt.</span><span class="sxs-lookup"><span data-stu-id="b36df-119">When "Just My Code" is enabled, Visual Studio in some cases will break on the line that throws the exception and display an error message that says "exception not handled by user code."</span></span> <span data-ttu-id="b36df-120">Dieser Fehler hat keine Auswirkungen.</span><span class="sxs-lookup"><span data-stu-id="b36df-120">This error is benign.</span></span> <span data-ttu-id="b36df-121">Sie können F5 drücken, um den Vorgang fortzusetzen. In diesem Fall wird das in den folgenden Beispielen veranschaulichte Ausnahmebehandlungsverhalten angewendet.</span><span class="sxs-lookup"><span data-stu-id="b36df-121">You can press F5 to continue and see the exception-handling behavior that is demonstrated in these examples.</span></span> <span data-ttu-id="b36df-122">Um zu verhindern, dass Visual Studio die Ausführung beim ersten Fehler unterbricht, deaktivieren Sie das Kontrollkästchen **Nur eigenen Code** unter **Extras, Optionen, Debugging, Allgemein**.</span><span class="sxs-lookup"><span data-stu-id="b36df-122">To prevent Visual Studio from breaking on the first error, just uncheck the **Enable Just My Code** checkbox under **Tools, Options, Debugging, General**.</span></span>

## <a name="attached-child-tasks-and-nested-aggregateexceptions"></a><span data-ttu-id="b36df-123">Angefügte untergeordnete Aufgaben und geschachtelte AggregateExceptions</span><span class="sxs-lookup"><span data-stu-id="b36df-123">Attached child tasks and nested AggregateExceptions</span></span>

<span data-ttu-id="b36df-124">Wenn eine Aufgabe über eine angefügte untergeordnete Aufgabe verfügt, die eine Ausnahme auslöst, wird diese Ausnahme in <xref:System.AggregateException> eingeschlossen, bevor sie an die übergeordnete Aufgabe weitergegeben wird, die diese Ausnahme in eine eigene <xref:System.AggregateException> einschließt und sie anschließend an den aufrufenden Thread zurückgibt.</span><span class="sxs-lookup"><span data-stu-id="b36df-124">If a task has an attached child task that throws an exception, that exception is wrapped in an <xref:System.AggregateException> before it is propagated to the parent task, which wraps that exception in its own <xref:System.AggregateException> before it propagates it back to the calling thread.</span></span> <span data-ttu-id="b36df-125">In solchen Fällen enthält die <xref:System.AggregateException.InnerExceptions%2A>-Eigenschaft der <xref:System.AggregateException>-Ausnahme, die bei den Methoden <xref:System.Threading.Tasks.Task.Wait%2A?displayProperty=nameWithType>, <xref:System.Threading.Tasks.Task.WaitAny%2A> oder <xref:System.Threading.Tasks.Task.WaitAll%2A> abgefangen wird, eine oder mehrere <xref:System.AggregateException>-Instanzen und nicht die ursprünglichen Ausnahmen, die den Fehler verursacht haben.</span><span class="sxs-lookup"><span data-stu-id="b36df-125">In such cases, the <xref:System.AggregateException.InnerExceptions%2A> property of the <xref:System.AggregateException> exception that is caught at the <xref:System.Threading.Tasks.Task.Wait%2A?displayProperty=nameWithType>, <xref:System.Threading.Tasks.Task.WaitAny%2A>, or <xref:System.Threading.Tasks.Task.WaitAll%2A> method contains one or more <xref:System.AggregateException> instances, not the original exceptions that caused the fault.</span></span> <span data-ttu-id="b36df-126">Um eine Iteration geschachtelter <xref:System.AggregateException>-Ausnahmen zu vermeiden, können Sie mit der <xref:System.AggregateException.Flatten%2A>-Methode alle geschachtelten <xref:System.AggregateException>-Ausnahmen entfernen, sodass die <xref:System.AggregateException.InnerExceptions%2A?displayProperty=nameWithType>-Eigenschaft die ursprünglichen Ausnahmen enthält.</span><span class="sxs-lookup"><span data-stu-id="b36df-126">To avoid having to iterate over nested <xref:System.AggregateException> exceptions, you can use the <xref:System.AggregateException.Flatten%2A> method to remove all the nested <xref:System.AggregateException> exceptions, so that the <xref:System.AggregateException.InnerExceptions%2A?displayProperty=nameWithType> property contains the original exceptions.</span></span> <span data-ttu-id="b36df-127">Im folgenden Beispiel werden geschachtelte <xref:System.AggregateException> -Instanzen vereinfacht und in nur einen Schleife behandelt.</span><span class="sxs-lookup"><span data-stu-id="b36df-127">In the following example, nested <xref:System.AggregateException> instances are flattened and handled in just one loop.</span></span>

[!code-csharp[TPL_Exceptions#22](../../../samples/snippets/csharp/VS_Snippets_Misc/tpl_exceptions/cs/flatten2.cs#22)]
[!code-vb[TPL_Exceptions#22](../../../samples/snippets/visualbasic/VS_Snippets_Misc/tpl_exceptions/vb/flatten2.vb#22)]

<span data-ttu-id="b36df-128">Sie können auch die <xref:System.AggregateException.Flatten%2A?displayProperty=nameWithType>-Methode verwenden, um die inneren Ausnahmen von mehreren <xref:System.AggregateException>-Instanzen erneut auszulösen, die von mehreren Aufgaben in einer einzelnen <xref:System.AggregateException>-Instanz ausgelöst wurden, wie im folgenden Beispiel gezeigt.</span><span class="sxs-lookup"><span data-stu-id="b36df-128">You can also use the <xref:System.AggregateException.Flatten%2A?displayProperty=nameWithType> method to rethrow the inner exceptions from multiple <xref:System.AggregateException> instances thrown by multiple tasks in a single <xref:System.AggregateException> instance, as the following example shows.</span></span>

[!code-csharp[TPL_Exceptions#13](../../../samples/snippets/csharp/VS_Snippets_Misc/tpl_exceptions/cs/taskexceptions2.cs#13)]
[!code-vb[TPL_Exceptions#13](../../../samples/snippets/visualbasic/VS_Snippets_Misc/tpl_exceptions/vb/taskexceptions2.vb#13)]

## <a name="exceptions-from-detached-child-tasks"></a><span data-ttu-id="b36df-129">Ausnahmen bei getrennten untergeordneten Aufgaben</span><span class="sxs-lookup"><span data-stu-id="b36df-129">Exceptions from detached child tasks</span></span>

<span data-ttu-id="b36df-130">Standardmäßig werden untergeordnete Aufgaben als getrennte Aufgaben erstellt.</span><span class="sxs-lookup"><span data-stu-id="b36df-130">By default, child tasks are created as detached.</span></span> <span data-ttu-id="b36df-131">Von getrennten Aufgaben ausgelöste Ausnahmen müssen in der unmittelbar übergeordneten Aufgabe behandelt oder erneut ausgelöst werden. Sie werden nicht auf die gleiche Weise wie angefügte untergeordnete Aufgaben an den aufrufenden Thread zurück geleitet.</span><span class="sxs-lookup"><span data-stu-id="b36df-131">Exceptions thrown from detached tasks must be handled or rethrown in the immediate parent task; they are not propagated back to the calling thread in the same way as attached child tasks propagated back.</span></span> <span data-ttu-id="b36df-132">Das übergeordnete Element der höchsten Ebene kann eine Ausnahme von einem getrennten untergeordneten Element manuell erneut auslösen, sodass diese in eine <xref:System.AggregateException> eingeschlossen und an den aufrufenden Thread zurück geleitet wird.</span><span class="sxs-lookup"><span data-stu-id="b36df-132">The topmost parent can manually rethrow an exception from a detached child to cause it to be wrapped in an <xref:System.AggregateException> and propagated back to the calling thread.</span></span>

[!code-csharp[TPL_Exceptions#23](../../../samples/snippets/csharp/VS_Snippets_Misc/tpl_exceptions/cs/detached21.cs#23)]
[!code-vb[TPL_Exceptions#23](../../../samples/snippets/visualbasic/VS_Snippets_Misc/tpl_exceptions/vb/detached21.vb#23)]

<span data-ttu-id="b36df-133">Selbst wenn Sie mithilfe einer Fortsetzung eine Ausnahme in einer untergeordneten Aufgabe beachten, muss die Ausnahme dennoch von der übergeordneten Aufgabe beachtet werden.</span><span class="sxs-lookup"><span data-stu-id="b36df-133">Even if you use a continuation to observe an exception in a child task, the exception still must be observed by the parent task.</span></span>

## <a name="exceptions-that-indicate-cooperative-cancellation"></a><span data-ttu-id="b36df-134">Ausnahmen mit kooperativem Abbruch</span><span class="sxs-lookup"><span data-stu-id="b36df-134">Exceptions that indicate cooperative cancellation</span></span>

<span data-ttu-id="b36df-135">Wenn Benutzercode in einer Aufgabe auf eine Abbruchanforderung reagiert, besteht das korrekte Verfahren darin, dass eine <xref:System.OperationCanceledException> ausgelöst wird, die in dem Abbruchtoken, in dem die Anforderung übermittelt wurde, übergeben wird.</span><span class="sxs-lookup"><span data-stu-id="b36df-135">When user code in a task responds to a cancellation request, the correct procedure is to throw an <xref:System.OperationCanceledException> passing in the cancellation token on which the request was communicated.</span></span> <span data-ttu-id="b36df-136">Bevor die Ausnahme weitergeleitet wird, vergleicht die Aufgabeninstanz das Token in der Ausnahme mit dem Token, das beim Erstellen an sie übergeben wurde.</span><span class="sxs-lookup"><span data-stu-id="b36df-136">Before it attempts to propagate the exception, the task instance compares the token in the exception to the one that was passed to it when it was created.</span></span> <span data-ttu-id="b36df-137">Stimmen beide Token überein, gibt die Aufgabe eine <xref:System.Threading.Tasks.TaskCanceledException> weiter, die in die <xref:System.AggregateException>eingeschlossen ist. Diese ist zu sehen, wenn die inneren Ausnahmen analysiert werden.</span><span class="sxs-lookup"><span data-stu-id="b36df-137">If they are the same, the task propagates a <xref:System.Threading.Tasks.TaskCanceledException> wrapped in the <xref:System.AggregateException>, and it can be seen when the inner exceptions are examined.</span></span> <span data-ttu-id="b36df-138">Wenn der aufrufende Thread jedoch nicht auf die Aufgabe wartet, wird diese Ausnahme nicht weitergegeben.</span><span class="sxs-lookup"><span data-stu-id="b36df-138">However, if the calling thread is not waiting on the task, this specific exception will not be propagated.</span></span> <span data-ttu-id="b36df-139">Weitere Informationen finden Sie unter [Aufgabenabbruch](task-cancellation.md).</span><span class="sxs-lookup"><span data-stu-id="b36df-139">For more information, see [Task Cancellation](task-cancellation.md).</span></span>

[!code-csharp[TPL_Exceptions#4](../../../samples/snippets/csharp/VS_Snippets_Misc/tpl_exceptions/cs/exceptions.cs#4)]
[!code-vb[TPL_Exceptions#4](../../../samples/snippets/visualbasic/VS_Snippets_Misc/tpl_exceptions/vb/tpl_exceptions.vb#4)]

## <a name="using-the-handle-method-to-filter-inner-exceptions"></a><span data-ttu-id="b36df-140">Filtern von inneren Ausnahmen mithilfe der Handle-Methode</span><span class="sxs-lookup"><span data-stu-id="b36df-140">Using the handle method to filter inner exceptions</span></span>

<span data-ttu-id="b36df-141">Mit der <xref:System.AggregateException.Handle%2A?displayProperty=nameWithType> -Methode können Sie Ausnahmen filtern, die ohne weitere Logik als "behandelt" definiert werden können.</span><span class="sxs-lookup"><span data-stu-id="b36df-141">You can use the <xref:System.AggregateException.Handle%2A?displayProperty=nameWithType> method to filter out exceptions that you can treat as "handled" without using any further logic.</span></span> <span data-ttu-id="b36df-142">Im Benutzerdelegaten, der an die <xref:System.AggregateException.Handle%28System.Func%7BSystem.Exception%2CSystem.Boolean%7D%29?displayProperty=nameWithType> -Methode weitergegeben wird, können Sie den Ausnahmetyp, seine <xref:System.Exception.Message%2A> -Eigenschaft oder beliebige andere Informationen analysieren und ermitteln, ob die Ausnahme keine Auswirkungen zeigt.</span><span class="sxs-lookup"><span data-stu-id="b36df-142">In the user delegate that is supplied to the <xref:System.AggregateException.Handle%28System.Func%7BSystem.Exception%2CSystem.Boolean%7D%29?displayProperty=nameWithType> method, you can examine the exception type, its <xref:System.Exception.Message%2A> property, or any other information about it that will let you determine whether it is benign.</span></span> <span data-ttu-id="b36df-143">Alle Ausnahmen, für die der Delegat `false` zurückgibt, werden in einer neuen <xref:System.AggregateException>-Instanz erneut ausgelöst, sobald die <xref:System.AggregateException.Handle%2A?displayProperty=nameWithType>-Methode zurückkehrt.</span><span class="sxs-lookup"><span data-stu-id="b36df-143">Any exceptions for which the delegate returns `false` are rethrown in a new <xref:System.AggregateException> instance immediately after the <xref:System.AggregateException.Handle%2A?displayProperty=nameWithType> method returns.</span></span>

<span data-ttu-id="b36df-144">Das folgende Beispiel ist zum ersten Beispiel dieses Themas funktional äquivalent, das jede Ausnahme in der <xref:System.AggregateException.InnerExceptions%2A?displayProperty=nameWithType>-Auflistung untersucht.</span><span class="sxs-lookup"><span data-stu-id="b36df-144">The following example is functionally equivalent to the first example in this topic, which examines each exception in the <xref:System.AggregateException.InnerExceptions%2A?displayProperty=nameWithType> collection.</span></span>  <span data-ttu-id="b36df-145">Dieser Ausnahmehandler ruft stattdessen das <xref:System.AggregateException.Handle%2A?displayProperty=nameWithType>-Methodenobjekt für jede Ausnahme auf und löst nur die Ausnahmen erneut aus, die keine `CustomException`-Instanzen sind.</span><span class="sxs-lookup"><span data-stu-id="b36df-145">Instead, this exception handler calls the <xref:System.AggregateException.Handle%2A?displayProperty=nameWithType> method object for each exception, and only rethrows exceptions that are not `CustomException` instances.</span></span>

[!code-csharp[TPL_Exceptions#26](../../../samples/snippets/csharp/VS_Snippets_Misc/tpl_exceptions/cs/handlemethod21.cs#26)]
[!code-vb[TPL_Exceptions#26](../../../samples/snippets/visualbasic/VS_Snippets_Misc/tpl_exceptions/vb/handlemethod21.vb#26)]

<span data-ttu-id="b36df-146">Nachfolgend finden Sie ein vollständigeres Beispiel, das die <xref:System.AggregateException.Handle%2A?displayProperty=nameWithType>-Methode verwendet, um beim Auflisten von Dateien für eine <xref:System.UnauthorizedAccessException>-Ausnahme eine besondere Behandlung zu bieten.</span><span class="sxs-lookup"><span data-stu-id="b36df-146">The following is a more complete example that uses the <xref:System.AggregateException.Handle%2A?displayProperty=nameWithType> method to provide special handling for an <xref:System.UnauthorizedAccessException> exception when enumerating files.</span></span>

[!code-csharp[TPL_Exceptions#12](../../../samples/snippets/csharp/VS_Snippets_Misc/tpl_exceptions/cs/taskexceptions.cs#12)]
[!code-vb[TPL_Exceptions#12](../../../samples/snippets/visualbasic/VS_Snippets_Misc/tpl_exceptions/vb/taskexceptions.vb#12)]

## <a name="observing-exceptions-by-using-the-taskexception-property"></a><span data-ttu-id="b36df-147">Berücksichtigen von Ausnahmen mit der Task.Exception-Eigenschaft</span><span class="sxs-lookup"><span data-stu-id="b36df-147">Observing exceptions by using the Task.Exception property</span></span>

<span data-ttu-id="b36df-148">Wenn eine Aufgabe mit einem <xref:System.Threading.Tasks.TaskStatus.Faulted?displayProperty=nameWithType> -Zustand abgeschlossen wird, kann die zugehörige <xref:System.Threading.Tasks.Task.Exception%2A> -Eigenschaft analysiert werden, um die spezifische Ausnahme zu ermitteln, die den Fehler verursacht hat.</span><span class="sxs-lookup"><span data-stu-id="b36df-148">If a task completes in the <xref:System.Threading.Tasks.TaskStatus.Faulted?displayProperty=nameWithType> state, its <xref:System.Threading.Tasks.Task.Exception%2A> property can be examined to discover which specific exception caused the fault.</span></span> <span data-ttu-id="b36df-149">Eine gute Möglichkeit, die <xref:System.Threading.Tasks.Task.Exception%2A> -Eigenschaft zu beachten, ist eine Fortsetzung, die nur bei einem Fehler in der vorausgehenden Aufgabe ausgeführt wird, wie im folgenden Beispiel gezeigt.</span><span class="sxs-lookup"><span data-stu-id="b36df-149">A good way to observe the <xref:System.Threading.Tasks.Task.Exception%2A> property is to use a continuation that runs only if the antecedent task faults, as shown in the following example.</span></span>

[!code-csharp[TPL_Exceptions#27](../../../samples/snippets/csharp/VS_Snippets_Misc/tpl_exceptions/cs/exceptionprop21.cs#27)]
[!code-vb[TPL_Exceptions#27](../../../samples/snippets/visualbasic/VS_Snippets_Misc/tpl_exceptions/vb/exceptionprop21.vb#27)]

<span data-ttu-id="b36df-150">In einer aussagekräftigen Anwendung würde der Fortsetzungsdelegat ausführliche Informationen zu der Ausnahme protokollieren und möglicherweise neue Tasks erzeugen, um nach der Ausnahme fortzufahren.</span><span class="sxs-lookup"><span data-stu-id="b36df-150">In a meaningful application, the continuation delegate could log detailed information about the exception and possibly spawn new tasks to recover from the exception.</span></span> <span data-ttu-id="b36df-151">Wenn bei einem Task ein Fehler auftritt, wird die Ausnahme durch die folgenden Ausdrücke ausgelöst:</span><span class="sxs-lookup"><span data-stu-id="b36df-151">If a task faults, the following expressions throw the exception:</span></span>

- `await task`
- `task.Wait()`
- `task.Result`
- `task.GetAwaiter().GetResult()`

<span data-ttu-id="b36df-152">Verwenden Sie eine [`try-catch`](../../csharp/language-reference/keywords/try-catch.md)-Anweisung, um ausgelöste Ausnahmen zu verarbeiten und zu beobachten.</span><span class="sxs-lookup"><span data-stu-id="b36df-152">Use a [`try-catch`](../../csharp/language-reference/keywords/try-catch.md) statement to handle and observe thrown exceptions.</span></span> <span data-ttu-id="b36df-153">Sie können auch die Ausnahme beobachten, indem Sie auf die <xref:System.Threading.Tasks.Task.Exception%2A?displayProperty=nameWithType>-Eigenschaft zugreifen.</span><span class="sxs-lookup"><span data-stu-id="b36df-153">Alternatively, observe the exception by accessing the <xref:System.Threading.Tasks.Task.Exception%2A?displayProperty=nameWithType> property.</span></span>

## <a name="unobservedtaskexception-event"></a><span data-ttu-id="b36df-154">UnobservedTaskException-Ereignis</span><span class="sxs-lookup"><span data-stu-id="b36df-154">UnobservedTaskException event</span></span>

<span data-ttu-id="b36df-155">In einigen Szenarien können häufig Ausnahmen ohne Auswirkungen auftreten (z. B. wenn Sie nicht vertrauenswürdige Plug-Ins hosten), und es kann schwierig sein, alle Ausnahmen manuell zu überwachen.</span><span class="sxs-lookup"><span data-stu-id="b36df-155">In some scenarios, such as when hosting untrusted plug-ins, benign exceptions might be common, and it might be too difficult to manually observe them all.</span></span> <span data-ttu-id="b36df-156">In diesen Fällen können Sie das <xref:System.Threading.Tasks.TaskScheduler.UnobservedTaskException?displayProperty=nameWithType> -Ereignis behandeln.</span><span class="sxs-lookup"><span data-stu-id="b36df-156">In these cases, you can handle the <xref:System.Threading.Tasks.TaskScheduler.UnobservedTaskException?displayProperty=nameWithType> event.</span></span> <span data-ttu-id="b36df-157">Mit der an den Handler übergebenen <xref:System.Threading.Tasks.UnobservedTaskExceptionEventArgs?displayProperty=nameWithType> -Instanz kann verhindert werden, dass die nicht überwachte Ausnahme wieder an den Verbindungsthread übergeben wird.</span><span class="sxs-lookup"><span data-stu-id="b36df-157">The <xref:System.Threading.Tasks.UnobservedTaskExceptionEventArgs?displayProperty=nameWithType> instance that is passed to your handler can be used to prevent the unobserved exception from being propagated back to the joining thread.</span></span>

## <a name="see-also"></a><span data-ttu-id="b36df-158">Siehe auch</span><span class="sxs-lookup"><span data-stu-id="b36df-158">See also</span></span>

- [<span data-ttu-id="b36df-159">Task Parallel Library (TPL)</span><span class="sxs-lookup"><span data-stu-id="b36df-159">Task Parallel Library (TPL)</span></span>](task-parallel-library-tpl.md)
